# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RegWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        Form.setFont(font)

        self.pushButtonStatus = QtWidgets.QPushButton(Form)
        self.pushButtonStatus.setGeometry(QtCore.QRect(354, 370, 231, 81))

        self.pushButtonStatus2 = QtWidgets.QPushButton(Form)
        self.pushButtonStatus2.setGeometry(QtCore.QRect(354, 370, 231, 81))

        self.pushButtonStatus3 = QtWidgets.QPushButton(Form)
        self.pushButtonStatus3.setGeometry(QtCore.QRect(354, 370, 231, 81))

        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)

        self.pushButtonStatus.setFont(font)
        self.pushButtonStatus.setObjectName("pushButtonStatus")

        self.pushButtonStatus2.setFont(font)
        self.pushButtonStatus2.setObjectName("pushButtonStatus2")

        self.pushButtonStatus3.setFont(font)
        self.pushButtonStatus3.setObjectName("pushButtonStatus3")

        self.labelStatus = QtWidgets.QLabel(Form)
        self.labelStatus.setGeometry(QtCore.QRect(20, 370, 301, 91))
        self.labelStatus.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelStatus.setTextFormat(QtCore.Qt.AutoText)
        self.labelStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStatus.setObjectName("labelStatus")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 601, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.labelTime = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelTime.setMinimumSize(QtCore.QSize(0, 50))
        self.labelTime.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.labelTime.setFont(font)
        self.labelTime.setObjectName("labelTime")
        self.gridLayout.addWidget(self.labelTime, 0, 2, 1, 1)
        self.comboBoxTime = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBoxTime.setMinimumSize(QtCore.QSize(0, 50))
        self.comboBoxTime.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.comboBoxTime.setFont(font)
        self.comboBoxTime.setObjectName("comboBoxTime")
        self.gridLayout.addWidget(self.comboBoxTime, 1, 2, 1, 1)
        self.comboBoxDate = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBoxDate.setMinimumSize(QtCore.QSize(0, 50))
        self.comboBoxDate.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.comboBoxDate.setFont(font)
        self.comboBoxDate.setObjectName("comboBoxDate")
        self.gridLayout.addWidget(self.comboBoxDate, 1, 1, 1, 1)
        self.labelDoc = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelDoc.setMinimumSize(QtCore.QSize(0, 50))
        self.labelDoc.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.labelDoc.setFont(font)
        self.labelDoc.setObjectName("labelDoc")
        self.gridLayout.addWidget(self.labelDoc, 0, 0, 1, 1)
        self.comboBoxDoc = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBoxDoc.setMinimumSize(QtCore.QSize(0, 50))
        self.comboBoxDoc.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.comboBoxDoc.setFont(font)
        self.comboBoxDoc.setObjectName("comboBoxDoc")
        self.gridLayout.addWidget(self.comboBoxDoc, 1, 0, 1, 1)
        self.labelDate = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelDate.setMinimumSize(QtCore.QSize(0, 50))
        self.labelDate.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.labelDate.setFont(font)
        self.labelDate.setObjectName("labelDate")
        self.gridLayout.addWidget(self.labelDate, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.labelFIO = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelFIO.setMinimumSize(QtCore.QSize(0, 50))
        self.labelFIO.setMaximumSize(QtCore.QSize(16777215, 50))
        self.labelFIO.setObjectName("labelFIO")
        self.verticalLayout.addWidget(self.labelFIO)
        self.textEditFIO = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textEditFIO.setMaximumSize(QtCore.QSize(16777215, 70))
        self.textEditFIO.setObjectName("textEditFIO")
        self.verticalLayout.addWidget(self.textEditFIO)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButtonStatus.setText(_translate("Form", "Подтвердить запись"))
        self.labelStatus.setText(_translate("Form", "Ошибка!\n"
"Запись уже существует"))
        self.labelTime.setText(_translate("Form", "Время:"))
        self.labelDoc.setText(_translate("Form", "Врач:"))
        self.labelDate.setText(_translate("Form", "Дата:"))
        self.labelFIO.setText(_translate("Form", "Введите ФИО пациента:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
