# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ChooseWhatEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 300)
        Form.setMinimumSize(QtCore.QSize(600, 300))
        Form.setMaximumSize(QtCore.QSize(600, 300))
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 601, 301))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 2, 2, 1, 1)
        self.pushButton_New_Doc = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_New_Doc.setMinimumSize(QtCore.QSize(210, 50))
        self.pushButton_New_Doc.setMaximumSize(QtCore.QSize(210, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pushButton_New_Doc.setFont(font)
        self.pushButton_New_Doc.setObjectName("pushButton_New_Doc")
        self.gridLayout.addWidget(self.pushButton_New_Doc, 1, 2, 1, 1)
        self.pushButton_New_Appoinment = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_New_Appoinment.setMinimumSize(QtCore.QSize(210, 50))
        self.pushButton_New_Appoinment.setMaximumSize(QtCore.QSize(210, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pushButton_New_Appoinment.setFont(font)
        self.pushButton_New_Appoinment.setObjectName("pushButton_New_Appoinment")
        self.gridLayout.addWidget(self.pushButton_New_Appoinment, 1, 1, 1, 1)
        self.pushButton_Cansel = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_Cansel.setMinimumSize(QtCore.QSize(100, 50))
        self.pushButton_Cansel.setMaximumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.pushButton_Cansel.setFont(font)
        self.pushButton_Cansel.setObjectName("pushButton_Cansel")
        self.gridLayout.addWidget(self.pushButton_Cansel, 1, 3, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 0, 2, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", ""))
        self.pushButton_New_Doc.setText(_translate("Form", "Создать нового доктора"))
        self.pushButton_New_Appoinment.setText(_translate("Form", "Создать новую запись"))
        self.pushButton_Cansel.setText(_translate("Form", "Отмена"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
